config/routes.rb
Rails.application.routes.draw do

  post '/stats', to: 'app#form_post', as: :compute
  get  '/stats' => redirect('/')

  get  '/stats/:username', to: 'app#stats', as: :user_stats

  root 'app#index', as: :home
end

app/models/repo_stats.rb
class RepoStats

  attr_reader :name, :url, :stars, :forks, :language, :score

  def initialize(id, name, url, stars, forks, language, score)
    @id = id
    @name = name
    @url = url
    @stars = stars
    @forks = forks
    @language = language
    @score = score
  end

end

app/models/user_stats.rb
class UserStats

  attr_reader :username, :name, :profile_url, :avatar_url, :repos, :languages, :orgs_user_belong, :score

=begin
  username
  image

  top languages

  points

  for each personal + org (repo stats):
    - owner/project
    - nbr stars
    - nbr forks

=end


  def initialize(id, username, name, profile_url, avatar_url, repo_stats, nbr_stared, nbr_forks, orgs_user_belong, score)
    @id = id
    @username = username
    @name = name
    @profile_url = profile_url
    @avatar_url = avatar_url
    @repos = repo_stats
    @nbr_stared = nbr_stared
    @nbr_forks = nbr_forks
    @orgs_user_belong = orgs_user_belong
    @score = score
  end

  def languages
   @languages ||= compute_languages
  end

  private def compute_languages
    langs = @repos.map(&:language).compact
    groupped = langs.group_by {|lang| lang}

    Rails.logger.debug "Computing user lang stats for #{@username} -> #{ @repos.map {|repo| [repo.name, repo.language]} }"

    count = {}
    groupped.each {|key, arr| count[key] = arr.size}
    count
  end

end

app/controllers/app_controller.rb
class AppController < ApplicationController

  def initialize
    super()
    @github = GithubService.new
  end

  def index; end

  def form_post
    if params[:username].blank?
      Rails.logger.warn 'No username received on request'
      redirect_to home_path, notice: 'Missing username'
    else
      redirect_to user_stats_path(params[:username])
    end
  end

  def stats
    username = params[:username]
    forced = params['forced'] ? true : false

    Rails.logger.debug "Stats for #{username} (forced=#{forced})"

    stats = @github.fetch_user_stats(username, forced)

    if stats.nil? # as for now, if we return nil it means username does not exist.
      redirect_to home_path, alert: "Invalid username: #{username}. The submitted username doesn't seem to exist on GitHub"
    else
      render locals: { stats: stats }
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/app_helper.rb
module AppHelper
  def level_label(score)
    case score
    when 0
      "Go for it! You are more than capable!"
    when 1..100
      "The first step is the hardest one 🎉"
    when 100..1000
      "It doesn't matter how slow you go, as long as you don't stop"
    when 1000..10000
      "On the path to become a rockstar, are you?"
    else
      return "The (open-source) world is yours!"
    end
  end
end

app/views/app/_footer.html.erb
<div class="row" id="bottom">
  <div class="col-md-4 text-left"><a class="black-link" href="https://pedrorijo.com/">pedrorijo.com</a></div>
  <div class="col-md-4 text-center"><a class="black-link" href="https://github.com/pedrorijo91/ross">pedrorijo91/ross</a></div>
  <div class="col-md-4 text-right">
    <a class="black-link" href="https://www.linkedin.com/in/pedrorijo91/"><i class="fab fa-linkedin fa-lg"></i></a>
    <a class="black-link" href="https://twitter.com/pedrorijo91"><i class="fab fa-twitter fa-lg"></i></a>
    <a class="black-link" href="https://github.com/pedrorijo91"><i class="fab fa-github fa-lg"></i></a>
    <a class="black-link" href="https://stackoverflow.com/users/4398050/pedrorijo91"><i class="fab fa-stack-overflow fa-lg"></i></a>
  </div>
</div>

app/views/app/_lang_line.html.erb
<tr>
  <th scope="row"><%= idx %></th>
  <td><%= lang %></td>
  <td>
    <% lang_image = lang.downcase.gsub('#', 'sharp').gsub('++', 'pp').gsub(" ", "-") + "-lang-icon.svg"

       if ActionController::Base.helpers.resolve_asset_path(lang_image) %>
      <%= image_tag(lang_image, width: '20px') %>
    <% end %>
  </td>
</tr>

app/views/app/_repo_line.html.erb
<tr>
  <th scope="row"><%= idx %></th>
  <td>
    <% if defined? repo_url %>
      <a href="<%= repo_url %>"><%= repo_name %></a>
    <% else %>
      <%= repo_name %>
    <% end %>
  </td>
  <td><%= repo_score %></td>
  <td><i class="far fa-star"></i> ️<%= repo_stars %></td>
  <td><i class="fas fa-code-branch"></i> <%= repo_forks %></td>
</tr>

app/views/app/_top_languages.html.erb
<p><strong>Top Languages</strong></p>
<table class="table table-striped table-sm">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Languages</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% stats.languages.sort_by {|_key, value| value}.reverse[0..9].each_with_index do |lang, idx| %>
    <%= render partial: 'lang_line', :locals => {:idx => idx + 1, :lang => lang[0]} %>
  <% end %>

  <% (10 - stats.languages.size).times do |index| %>
    <%= render partial: 'lang_line', :locals => {:idx => stats.languages.size + index + 1, :lang => '-'} %>
  <% end %>
  </tbody>
</table>

app/views/app/_top_repos.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">

  <li class="nav-item">
    <a class="nav-link active" id="personal-tab" data-toggle="tab" href="#personal" role="tab" aria-controls="personal" aria-selected="true">Personal</a>
  </li>

  <% stats.orgs_user_belong.sort.each do |org| %>
    <li class="nav-item">
      <a class="nav-link" id="org-<%= org %>-tab" data-toggle="tab" href="#org-<%= org %>" role="tab" aria-controls="org-<%= org %>" aria-selected="false">
        <%= org %> <span class="badge badge-light">org</span>
      </a>
    </li>
  <% end %>

</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="personal" role="tabpanel" aria-labelledby="personal-tab">
    <table class="table table-striped table-sm">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Repository</th>
        <th scope="col">Score</th>
        <th scope="col">Stars</th>
        <th scope="col">Forks</th>
      </tr>
      </thead>
      <tbody>
      <% stats.repos.sort_by(&:score).reverse[0..9].each_with_index do |repo, idx| %>
        <%= render partial: 'repo_line', :locals => {:idx => idx + 1, :repo_url => repo.url, :repo_name => stats.username + '/' + repo.name, :repo_score => repo.score, :repo_stars => repo.stars, :repo_forks => repo.forks} %>
      <% end %>

      <% (10 - stats.repos.size).times do |index| %>
        <%= render partial: 'repo_line', :locals => {:idx =>  stats.repos.size + index + 1, :repo_name => '-', :repo_score => '-', :repo_stars => '-', :repo_forks => '-', :stats => stats} %>
      <% end %>
      </tbody>
    </table>
  </div>

  <% stats.orgs_user_belong.each do |org| %>
    <div class="tab-pane fade" id="org-<%= org %>" role="tabpanel" aria-labelledby="org-<%= org %>-tab">
      Soon :)
    </div>
  <% end %>

</div>

app/views/app/index.html.erb
<div class="container h-100">

  <div class="row justify-content-center">
    <h1 class="display-3 title">Welcome to the Open-Source contributor game!</h1>
  </div>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <% if notice %>
    <div class="alert alert-warning" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="row h-75 justify-content-center align-items-center">
    <%= form_with url: compute_path, local: true, class: "form-inline justify-content-center" do |form| %>
      <%= form.label :username, "GitHub Username", class: "sr-only" %>
      <%= form.text_field :username, required: true, class: "form-control mb-2 mr-sm-2", placeholder: "GitHub username" %>
      <%= form.submit "Compute my stats", class: "btn btn-primary mb-2" %>
    <% end %>
  </div>

</div>

app/views/app/stats.html.erb
<div class="container">

  <div class="row justify-content-center">
    <h1 class="display-3 title">The Open Source Game</h1>
  </div>

  <div class="row" id="top">
    <div class="col-md-3">
      <div class="row">
        <figure>
          <a href="<%= stats.profile_url %>"><img class="img-thumbnail row-height" src="<%= stats.avatar_url %>"></a>
          <figcaption><a href="<%= stats.profile_url %>"><%= stats.name %> (@<%= stats.username %>)</a></figcaption>
        </figure>
      </div>
    </div>
    <div class="row col-md-6 justify-content-center">
      <h2 class="display-4"><%= stats.score %> points</h2>
      <h3 class="display-5"><%= level_label(stats.score) %></h3>
    </div>
    <div class="col-md-3">
      <div class="row justify-content-center">
        <img class="row-height" src="https://i.pinimg.com/originals/41/36/16/41361625cc44df07f81a620eac766468.png">
      </div>
      <div class="row justify-content-center">
        <a class="twitter-share-button"
           href=<%= "https://twitter.com/intent/tweet?text=" + ERB::Util.url_encode("I just got #{stats.score} points for my Open Source contributions! What about you?") %>
           <%= ENV['FOOTER_ENABLED'] == 'true' ?  'data-via=pedrorijo91' : '' %>
           data-hashtags="OpenSource,oss,foss"
           data-size="large">
          Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
      <div class="row justify-content-center">
        <%= link_to("I want to check my profile!", :home) %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <%= render partial: 'top_repos', :locals => {:stats => stats} %>
    </div>
    <div class="col-md-3">
      <%= render partial: 'top_languages', :locals => {:stats => stats} %>
    </div>
  </div>

  <% if ENV['FOOTER_ENABLED'] == 'true' %>
    <%= render 'footer' %>
  <% end %>

</div>

app/views/layouts/_ga.html.erb
<% if Rails.env.production? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-61168333-4"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-61168333-4');
  </script>
<% else %>
  <span class="empty-ga"></span>
<% end %>

app/views/layouts/_hotjar.html.erb
<% if Rails.env.production? %>
  <!-- Hotjar Tracking Code for https://r-oss.herokuapp.com -->
  <script>
      (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:1513231,hjsv:6};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
  </script>
<% else %>
  <span class="empty-hotjar"></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ross</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/ga' %>
    <%= render 'layouts/hotjar' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>